<?php

namespace App\Domain\Authorization;

enum AuthorizationReason: string
{
    case ALLOWED = 'ALLOWED';
    case BLOCKED = 'BLOCKED';
    case INSUFFICIENT_RELATIONSHIP = 'INSUFFICIENT_RELATIONSHIP';
    case VERIFICATION_REQUIRED = 'VERIFICATION_REQUIRED';
    case NO_EXPLICIT_GRANT = 'NO_EXPLICIT_GRANT';
    case RESOURCE_EXPIRED = 'RESOURCE_EXPIRED';
    case RESOURCE_DELETED = 'RESOURCE_DELETED';
    case SELF_ACTION_FORBIDDEN = 'SELF_ACTION_FORBIDDEN';
    case INACTIVE_USER = 'INACTIVE_USER';
    case NOT_DISCOVERABLE = 'NOT_DISCOVERABLE';
    case NOT_IN_ACTIVE_ZONE = 'NOT_IN_ACTIVE_ZONE';
    case MATCH_EXPIRED = 'MATCH_EXPIRED';
    case FRIENDSHIP_ENDED = 'FRIENDSHIP_ENDED';
    case CONVERSATION_ENDED = 'CONVERSATION_ENDED';
    case MAX_LIMIT_REACHED = 'MAX_LIMIT_REACHED';
    case INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION';
    case UNAUTHORIZED = 'UNAUTHORIZED';
}